#! /bin/sh
cd ../../
rm -R bin/
mkdir bin/

#Actualiza las rutas de archivos .java
find ./src -iname *.java > scripts/routes

#Copia los archivos de la carpeta de recursos a bin
cp -r src/res bin/res

javac -Xlint:unchecked -Xdiags:verbose -d bin @scripts/routes
